#pragma once

#define MIJIA_POWER_VERSION_MAJOR 1
#define MIJIA_POWER_VERSION_MINOR 1
#define MIJIA_POWER_VERSION_PATCH 0
#define MIJIA_POWER_VERSION_BUILD 0

#define MIJIA_POWER_VERSION_NUMERIC MIJIA_POWER_VERSION_MAJOR,MIJIA_POWER_VERSION_MINOR,MIJIA_POWER_VERSION_PATCH,MIJIA_POWER_VERSION_BUILD
#define MIJIA_POWER_VERSION_STRING  "1.1.0.0"
#define MIJIA_POWER_VERSION_STRING_W L"1.1.0"

#define MIJIA_POWER_FILE_DESCRIPTION "米家插座功率 TrafficMonitor 插件"
#define MIJIA_POWER_FILE_DESCRIPTION_W L"米家插座功率 TrafficMonitor 插件"
#define MIJIA_POWER_PRODUCT_NAME     "MijiaPowerPlugin"
#define MIJIA_POWER_INTERNAL_NAME    "MijiaPower"
#define MIJIA_POWER_ORIGINAL_NAME    "MijiaPower.dll"
#define MIJIA_POWER_COMPANY_NAME     "gilnatab"
#define MIJIA_POWER_COPYRIGHT        "Copyright (C) 2026 gilnatab"
#define MIJIA_POWER_COPYRIGHT_W      L"2026 gilnatab"
